import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const actionRoot = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(actionRoot, "../..");
const outputPath = resolve(actionRoot, "dist/index.js");
const check = process.argv.includes("--check");

const result = await build({
  absWorkingDir: repositoryRoot,
  alias: {
    "@aicorg/rely": resolve(repositoryRoot, "packages/rely/src/index.ts"),
    "@aicorg/spec": resolve(repositoryRoot, "packages/spec/src/index.ts"),
    "@aicorg/verify-core": resolve(repositoryRoot, "packages/verify-core/src/index.ts")
  },
  banner: {
    js: "/*! AIC reliance action verifier bundle. Apache-2.0. Generated by actions/aic-rely/build.mjs; do not hand-edit. */"
  },
  bundle: true,
  entryPoints: [resolve(actionRoot, "src/main.ts")],
  format: "esm",
  legalComments: "none",
  logLevel: "silent",
  metafile: true,
  minify: true,
  outfile: outputPath,
  platform: "node",
  sourcemap: false,
  target: "node24",
  treeShaking: true,
  write: false
});

const output = result.outputFiles?.find((file) => file.path === outputPath);
if (!output) throw new Error("esbuild did not produce the expected action bundle.");
const allowedRuntimeImports = new Set([
  "node:crypto",
  "node:fs/promises",
  "node:path",
  "node:url"
]);
const unsupportedImports = Object.values(result.metafile?.outputs ?? {})
  .flatMap((entry) => entry.imports)
  .filter((entry) => entry.external && !allowedRuntimeImports.has(entry.path));
if (unsupportedImports.length > 0) {
  throw new Error(
    `Action bundle contains an unapproved runtime import: ${unsupportedImports.map((entry) => entry.path).join(", ")}`
  );
}

if (check) {
  const committed = await readFile(outputPath).catch(() => undefined);
  if (!committed || !committed.equals(output.contents)) {
    throw new Error("Committed dist/index.js is stale. Run `npm run build` in actions/aic-rely.");
  }
  console.log("AIC reliance action bundle is reproducible and current.");
} else {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output.contents);
  console.log(`Wrote ${outputPath} (${output.contents.length} bytes).`);
}
